### ISSUE TITLE
Bad Header When opening scratch 2.0 projects

### ISSUE THREAD

**Issue by walterigo** [NoMod-Programming/Whiskers#1]
Hi
    I am getting a  error bad header message when I try to open a scratch 2.0 project.
I am on ubuntu 64bit system  opening the .exe through Wine. (windows emulator) due to cant get squeak 5 installed.
    I also just wanted to say thanks for your work. My Son loves scratch and we are making a Banana pi M3 arcade machine out of a  old icade. the project should cost around 200.00  Completed.  But as you know Scratch 2.0  doesn't  run on the pi.

![icade](https://cloud.githubusercontent.com/assets/17354024/13196789/28efd9d6-d796-11e5-8846-c13d229980b8.jpg)

**Comment by NoMod-Programming** [comment]
It looks like I forgot to add the SB2 compatibility to the NuWhiskers release. I'll have a version that runs this out within a few hours.

BTW: Good luck with your project! It sounds cool :smiley:

**Comment by Jonathan50** [comment]
Er you called the label '**scrach 2 - compatibility**'

**Comment by NoMod-Programming** [comment]
> Er you called the label '**scratch 2 - compatability**'
What???

**Comment by Jonathan50** [comment]
should be scra**T**ch 2

**Comment by NoMod-Programming** [comment]
Whoops... Fixing that now.

**Comment by NoMod-Programming** [comment]
Sorry for the year-long wait. But I have a version that can fully load an SB2 project here: https://drive.google.com/open?id=0B6FRCf6PuzM9bmxOOE4wczgwa0E

I'll be fixing the bugs with the custom block's hat color in the next version, but this one runs an sb2 file pretty smoothly on the pi. I've tested it on a VM with 128mb of ram and a virtual 400mhz cpu, so it should run quickly on the pi.
